import { supabase } from "@/integrations/supabase/client";

// The v2_* tables / rpc_v2_* functions / v_v2_* views are not in the generated
// Database types until the migration is applied + types.ts regenerated by
// Lovable. Until then we go through an untyped client. Tighten after apply.
const sb = supabase as unknown as {
  from: (t: string) => any;
  rpc: (fn: string, args?: Record<string, unknown>) => any;
};

export async function listV2Schedules(siteId: string) {
  const { data, error } = await sb
    .from("v2_service_schedules")
    .select("id, code, name, expected_weekday, planned_duration_hours, display_summary")
    .eq("site_id", siteId)
    .is("archived_at", null)
    .order("expected_weekday");
  if (error) throw error;
  return (data ?? []) as any[];
}

export async function listV2Visits(siteId: string) {
  const { data, error } = await sb
    .from("v2_visit_instances")
    .select("id, visit_date, status, service_schedule_id, v2_service_schedules(name)")
    .eq("site_id", siteId)
    .order("visit_date", { ascending: false })
    .limit(50);
  if (error) throw error;
  return (data ?? []) as any[];
}

export async function createV2Visit(
  siteId: string,
  scheduleId: string,
  visitDate: string,
): Promise<string> {
  const { data, error } = await sb.rpc("rpc_v2_create_visit", {
    p_site_id: siteId,
    p_service_schedule_id: scheduleId,
    p_visit_date: visitDate,
  });
  if (error) throw error;
  return data as string;
}

export async function regenerateV2Visit(visitInstanceId: string): Promise<number> {
  const { data, error } = await sb.rpc("rpc_v2_generate_visit_tasks", {
    p_visit_instance_id: visitInstanceId,
  });
  if (error) throw error;
  return (data as number) ?? 0;
}

export async function getV2VisitReport(visitInstanceId: string) {
  const { data, error } = await sb
    .from("v_v2_visit_task_report")
    .select("*")
    .eq("visit_instance_id", visitInstanceId)
    .order("task_source")
    .order("area");
  if (error) throw error;
  return (data ?? []) as any[];
}

export async function recordV2Result(args: {
  taskId: string;
  status: string;
  rating: number | null;
  isNa: boolean;
  naReason?: string | null;
  operativeNote?: string | null;
  followUp?: boolean;
}) {
  const { error } = await sb.rpc("rpc_v2_record_result", {
    p_generated_visit_task_id: args.taskId,
    p_status: args.status || null,
    p_rating: args.isNa ? null : args.rating,
    p_is_na: args.isNa,
    p_na_reason: args.naReason ?? null,
    p_operative_note: args.operativeNote ?? null,
    p_follow_up_required: args.followUp ?? false,
  });
  if (error) throw error;
}

export async function verifyV2Task(taskId: string, verified: boolean, note?: string) {
  const { error } = await sb.rpc("rpc_v2_supervisor_verify", {
    p_generated_visit_task_id: taskId,
    p_verified: verified,
    p_supervisor_note: note ?? null,
  });
  if (error) throw error;
}
