import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { listSites } from "@/lib/tms/queries";
import {
  listV2Schedules,
  listV2Visits,
  createV2Visit,
  regenerateV2Visit,
  getV2VisitReport,
  recordV2Result,
  verifyV2Task,
} from "@/lib/tms/v2";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/v2/visits")({
  component: V2Visits,
});

const SOURCE_LABEL: Record<string, string> = {
  baseline: "Baseline (always due)",
  rotation: "Rotation (active segment)",
  carry_forward: "Carry-forward",
  one_off: "One-off",
  optional: "Optional",
  out_of_scope_observation: "Out-of-scope observation",
};

const STATUS_OPTIONS = [
  ["completed", "Completed"],
  ["partial", "Partial"],
  ["not_completed", "Not completed"],
  ["inaccessible", "Inaccessible"],
  ["not_applicable", "Not applicable"],
] as const;

function outcomeBadge(outcome: string) {
  const map: Record<string, string> = {
    completed: "bg-green-100 text-green-800 dark:bg-green-950/50 dark:text-green-300",
    failed: "bg-red-100 text-red-800 dark:bg-red-950/50 dark:text-red-300",
    missed: "bg-red-100 text-red-800 dark:bg-red-950/50 dark:text-red-300",
    partial: "bg-amber-100 text-amber-800 dark:bg-amber-950/50 dark:text-amber-300",
    due_not_recorded: "bg-muted text-muted-foreground",
    "n/a": "bg-muted text-muted-foreground",
    recorded: "bg-muted text-muted-foreground",
  };
  return map[outcome] ?? "bg-muted text-muted-foreground";
}

function V2Visits() {
  const qc = useQueryClient();
  const sites = useQuery({ queryKey: ["sites"], queryFn: listSites });

  const [siteId, setSiteId] = useState("");
  const [scheduleId, setScheduleId] = useState("");
  const [visitDate, setVisitDate] = useState("");
  const [visitId, setVisitId] = useState("");

  // Default to Abbey (or the first accessible site).
  useEffect(() => {
    if (!siteId && sites.data && sites.data.length > 0) {
      const abbey = sites.data.find((s) => s.code === "ABBEY_LC");
      setSiteId(abbey?.id ?? sites.data[0].id);
    }
  }, [sites.data, siteId]);

  const schedules = useQuery({
    queryKey: ["v2-schedules", siteId],
    queryFn: () => listV2Schedules(siteId),
    enabled: !!siteId,
  });
  const visits = useQuery({
    queryKey: ["v2-visits", siteId],
    queryFn: () => listV2Visits(siteId),
    enabled: !!siteId,
  });
  const report = useQuery({
    queryKey: ["v2-report", visitId],
    queryFn: () => getV2VisitReport(visitId),
    enabled: !!visitId,
  });

  const create = useMutation({
    mutationFn: () => createV2Visit(siteId, scheduleId, visitDate),
    onSuccess: (id) => {
      toast.success("Visit ready — tasks generated by the database");
      setVisitId(id);
      qc.invalidateQueries({ queryKey: ["v2-visits", siteId] });
      qc.invalidateQueries({ queryKey: ["v2-report", id] });
    },
    onError: (e: any) => toast.error(e.message ?? "Create failed"),
  });

  const regen = useMutation({
    mutationFn: () => regenerateV2Visit(visitId),
    onSuccess: () => {
      toast.success("Regenerated (carry-forward refreshed)");
      qc.invalidateQueries({ queryKey: ["v2-report", visitId] });
    },
    onError: (e: any) => toast.error(e.message),
  });

  const rows = (report.data ?? []) as any[];
  const grouped = useMemo(() => {
    const g: Record<string, any[]> = {};
    for (const r of rows) (g[r.task_source] ??= []).push(r);
    return g;
  }, [rows]);

  const summary = useMemo(() => {
    const s = { due: 0, completed: 0, missed: 0, failed: 0, carry: 0 };
    for (const r of rows) {
      if (r.is_due) s.due++;
      if (r.outcome === "completed") s.completed++;
      if (r.outcome === "missed") s.missed++;
      if (r.outcome === "failed") s.failed++;
      if (r.task_source === "carry_forward") s.carry++;
    }
    return s;
  }, [rows]);

  return (
    <div className="space-y-6">
      <header>
        <h1 className="text-2xl font-semibold tracking-tight">Abbey v2 — visits</h1>
        <p className="text-sm text-muted-foreground">
          Database-driven. The server decides which tasks are due; this page only
          displays and records.
        </p>
      </header>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Create / open a visit</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-3 sm:grid-cols-4">
          <div className="space-y-1">
            <Label>Site</Label>
            <select
              className="w-full border rounded-md px-2 py-1.5 bg-background text-sm"
              value={siteId}
              onChange={(e) => {
                setSiteId(e.target.value);
                setScheduleId("");
                setVisitId("");
              }}
            >
              {(sites.data ?? []).map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                </option>
              ))}
            </select>
          </div>
          <div className="space-y-1">
            <Label>Service schedule</Label>
            <select
              className="w-full border rounded-md px-2 py-1.5 bg-background text-sm"
              value={scheduleId}
              onChange={(e) => setScheduleId(e.target.value)}
              disabled={!siteId}
            >
              <option value="">Select…</option>
              {(schedules.data ?? []).map((s: any) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                </option>
              ))}
            </select>
          </div>
          <div className="space-y-1">
            <Label>Visit date</Label>
            <Input type="date" value={visitDate} onChange={(e) => setVisitDate(e.target.value)} />
          </div>
          <div className="flex items-end">
            <Button
              className="w-full"
              disabled={!siteId || !scheduleId || !visitDate || create.isPending}
              onClick={() => create.mutate()}
            >
              {create.isPending ? "Generating…" : "Create / open"}
            </Button>
          </div>
        </CardContent>
      </Card>

      {(visits.data?.length ?? 0) > 0 && (
        <div className="space-y-1">
          <Label className="text-xs">Recent v2 visits</Label>
          <div className="flex flex-wrap gap-2">
            {(visits.data ?? []).map((v: any) => (
              <Button
                key={v.id}
                size="sm"
                variant={v.id === visitId ? "default" : "outline"}
                onClick={() => setVisitId(v.id)}
              >
                {v.v2_service_schedules?.name ?? "Visit"} · {v.visit_date}
              </Button>
            ))}
          </div>
        </div>
      )}

      {visitId && (
        <Card>
          <CardHeader className="flex flex-row items-center justify-between">
            <CardTitle className="text-base">
              Generated tasks
              <span className="ml-2 text-xs font-normal text-muted-foreground">
                due {summary.due} · completed {summary.completed} · missed {summary.missed} ·
                failed {summary.failed} · carry-forward {summary.carry}
              </span>
            </CardTitle>
            <Button size="sm" variant="outline" onClick={() => regen.mutate()} disabled={regen.isPending}>
              Regenerate
            </Button>
          </CardHeader>
          <CardContent className="space-y-4">
            {report.isLoading && <p className="text-sm text-muted-foreground">Loading…</p>}
            {report.isSuccess && rows.length === 0 && (
              <p className="text-sm text-muted-foreground">
                No tasks. If this schedule has a rotation, its anchor may be unset.
              </p>
            )}
            {Object.entries(grouped).map(([source, list]) => (
              <div key={source} className="space-y-2">
                <div className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                  {SOURCE_LABEL[source] ?? source}
                  <Badge variant="secondary" className="ml-2">
                    {list.length}
                  </Badge>
                </div>
                {list.map((r) => (
                  <TaskRow key={r.generated_visit_task_id} row={r} onChanged={() => report.refetch()} />
                ))}
              </div>
            ))}
          </CardContent>
        </Card>
      )}
    </div>
  );
}

function TaskRow({ row, onChanged }: { row: any; onChanged: () => void }) {
  const [status, setStatus] = useState<string>(row.status ?? "");
  const [rating, setRating] = useState<number | null>(row.is_na ? null : (row.rating ?? null));
  const [isNa, setIsNa] = useState<boolean>(!!row.is_na);

  const save = useMutation({
    mutationFn: () =>
      recordV2Result({
        taskId: row.generated_visit_task_id,
        status,
        rating,
        isNa,
        naReason: isNa ? "n/a" : null,
      }),
    onSuccess: () => {
      toast.success("Recorded");
      onChanged();
    },
    onError: (e: any) => toast.error(e.message),
  });

  const verify = useMutation({
    mutationFn: () => verifyV2Task(row.generated_visit_task_id, true),
    onSuccess: () => {
      toast.success("Verified");
      onChanged();
    },
    onError: (e: any) => toast.error(e.message),
  });

  return (
    <div className="rounded-md border p-2 text-sm space-y-2">
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0">
          <div className="font-medium">{row.task}</div>
          <div className="text-xs text-muted-foreground">
            {row.area}
            {row.sub_area ? ` · ${row.sub_area}` : ""}
          </div>
        </div>
        <div className="flex items-center gap-1 shrink-0">
          {row.requires_supervisor_verification && (
            <Badge variant="outline">verify</Badge>
          )}
          <span className={`rounded px-1.5 py-0.5 text-xs font-medium ${outcomeBadge(row.outcome)}`}>
            {row.outcome}
          </span>
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-2">
        <select
          className="border rounded-md px-2 py-1 bg-background text-xs"
          value={status}
          onChange={(e) => setStatus(e.target.value)}
        >
          <option value="">status…</option>
          {STATUS_OPTIONS.map(([v, l]) => (
            <option key={v} value={v}>
              {l}
            </option>
          ))}
        </select>
        <div className="flex gap-1">
          {[1, 2, 3, 4, 5].map((n) => (
            <Button
              key={n}
              size="sm"
              variant={!isNa && rating === n ? "default" : "outline"}
              onClick={() => {
                setRating(n);
                setIsNa(false);
              }}
            >
              {n}
            </Button>
          ))}
          <Button
            size="sm"
            variant={isNa ? "default" : "outline"}
            onClick={() => {
              setIsNa(true);
              setRating(null);
            }}
          >
            N/A
          </Button>
        </div>
        <Button size="sm" onClick={() => save.mutate()} disabled={save.isPending}>
          Save
        </Button>
        {row.requires_supervisor_verification && (
          <Button
            size="sm"
            variant={row.supervisor_verified ? "secondary" : "outline"}
            onClick={() => verify.mutate()}
            disabled={verify.isPending}
          >
            {row.supervisor_verified ? "Verified ✓" : "Verify"}
          </Button>
        )}
      </div>
    </div>
  );
}
