/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFieldGuideRouteImport } from './routes/_authenticated/field-guide'
import { Route as AuthenticatedVisitsIndexRouteImport } from './routes/_authenticated/visits.index'
import { Route as AuthenticatedActionsIndexRouteImport } from './routes/_authenticated/actions.index'
import { Route as AuthenticatedVisitsNewRouteImport } from './routes/_authenticated/visits.new'
import { Route as AuthenticatedVisitsVisitIdRouteImport } from './routes/_authenticated/visits.$visitId'
import { Route as AuthenticatedV2VisitsRouteImport } from './routes/_authenticated/v2.visits'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedActionsActionIdRouteImport } from './routes/_authenticated/actions.$actionId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldGuideRoute = AuthenticatedFieldGuideRouteImport.update({
  id: '/field-guide',
  path: '/field-guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitsIndexRoute =
  AuthenticatedVisitsIndexRouteImport.update({
    id: '/visits/',
    path: '/visits/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActionsIndexRoute =
  AuthenticatedActionsIndexRouteImport.update({
    id: '/actions/',
    path: '/actions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisitsNewRoute = AuthenticatedVisitsNewRouteImport.update({
  id: '/visits/new',
  path: '/visits/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitsVisitIdRoute =
  AuthenticatedVisitsVisitIdRouteImport.update({
    id: '/visits/$visitId',
    path: '/visits/$visitId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedV2VisitsRoute = AuthenticatedV2VisitsRouteImport.update({
  id: '/v2/visits',
  path: '/v2/visits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActionsActionIdRoute =
  AuthenticatedActionsActionIdRouteImport.update({
    id: '/actions/$actionId',
    path: '/actions/$actionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/field-guide': typeof AuthenticatedFieldGuideRoute
  '/actions/$actionId': typeof AuthenticatedActionsActionIdRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/v2/visits': typeof AuthenticatedV2VisitsRoute
  '/visits/$visitId': typeof AuthenticatedVisitsVisitIdRoute
  '/visits/new': typeof AuthenticatedVisitsNewRoute
  '/actions/': typeof AuthenticatedActionsIndexRoute
  '/visits/': typeof AuthenticatedVisitsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/field-guide': typeof AuthenticatedFieldGuideRoute
  '/': typeof AuthenticatedIndexRoute
  '/actions/$actionId': typeof AuthenticatedActionsActionIdRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/v2/visits': typeof AuthenticatedV2VisitsRoute
  '/visits/$visitId': typeof AuthenticatedVisitsVisitIdRoute
  '/visits/new': typeof AuthenticatedVisitsNewRoute
  '/actions': typeof AuthenticatedActionsIndexRoute
  '/visits': typeof AuthenticatedVisitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/field-guide': typeof AuthenticatedFieldGuideRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/actions/$actionId': typeof AuthenticatedActionsActionIdRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/v2/visits': typeof AuthenticatedV2VisitsRoute
  '/_authenticated/visits/$visitId': typeof AuthenticatedVisitsVisitIdRoute
  '/_authenticated/visits/new': typeof AuthenticatedVisitsNewRoute
  '/_authenticated/actions/': typeof AuthenticatedActionsIndexRoute
  '/_authenticated/visits/': typeof AuthenticatedVisitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/field-guide'
    | '/actions/$actionId'
    | '/admin/users'
    | '/v2/visits'
    | '/visits/$visitId'
    | '/visits/new'
    | '/actions/'
    | '/visits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/field-guide'
    | '/'
    | '/actions/$actionId'
    | '/admin/users'
    | '/v2/visits'
    | '/visits/$visitId'
    | '/visits/new'
    | '/actions'
    | '/visits'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/field-guide'
    | '/_authenticated/'
    | '/_authenticated/actions/$actionId'
    | '/_authenticated/admin/users'
    | '/_authenticated/v2/visits'
    | '/_authenticated/visits/$visitId'
    | '/_authenticated/visits/new'
    | '/_authenticated/actions/'
    | '/_authenticated/visits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field-guide': {
      id: '/_authenticated/field-guide'
      path: '/field-guide'
      fullPath: '/field-guide'
      preLoaderRoute: typeof AuthenticatedFieldGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits/': {
      id: '/_authenticated/visits/'
      path: '/visits'
      fullPath: '/visits/'
      preLoaderRoute: typeof AuthenticatedVisitsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actions/': {
      id: '/_authenticated/actions/'
      path: '/actions'
      fullPath: '/actions/'
      preLoaderRoute: typeof AuthenticatedActionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits/new': {
      id: '/_authenticated/visits/new'
      path: '/visits/new'
      fullPath: '/visits/new'
      preLoaderRoute: typeof AuthenticatedVisitsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits/$visitId': {
      id: '/_authenticated/visits/$visitId'
      path: '/visits/$visitId'
      fullPath: '/visits/$visitId'
      preLoaderRoute: typeof AuthenticatedVisitsVisitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/v2/visits': {
      id: '/_authenticated/v2/visits'
      path: '/v2/visits'
      fullPath: '/v2/visits'
      preLoaderRoute: typeof AuthenticatedV2VisitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actions/$actionId': {
      id: '/_authenticated/actions/$actionId'
      path: '/actions/$actionId'
      fullPath: '/actions/$actionId'
      preLoaderRoute: typeof AuthenticatedActionsActionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFieldGuideRoute: typeof AuthenticatedFieldGuideRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedActionsActionIdRoute: typeof AuthenticatedActionsActionIdRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedV2VisitsRoute: typeof AuthenticatedV2VisitsRoute
  AuthenticatedVisitsVisitIdRoute: typeof AuthenticatedVisitsVisitIdRoute
  AuthenticatedVisitsNewRoute: typeof AuthenticatedVisitsNewRoute
  AuthenticatedActionsIndexRoute: typeof AuthenticatedActionsIndexRoute
  AuthenticatedVisitsIndexRoute: typeof AuthenticatedVisitsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFieldGuideRoute: AuthenticatedFieldGuideRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedActionsActionIdRoute: AuthenticatedActionsActionIdRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedV2VisitsRoute: AuthenticatedV2VisitsRoute,
  AuthenticatedVisitsVisitIdRoute: AuthenticatedVisitsVisitIdRoute,
  AuthenticatedVisitsNewRoute: AuthenticatedVisitsNewRoute,
  AuthenticatedActionsIndexRoute: AuthenticatedActionsIndexRoute,
  AuthenticatedVisitsIndexRoute: AuthenticatedVisitsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
